# Generated by Django 5.2.8 on 2025-12-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practica',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.AddField(
            model_name='practica',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='practica',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
