# Generated by Django 5.2.8 on 2025-12-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruapp', '0003_add_imagen_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practica',
            options={},
        ),
        migrations.RemoveField(
            model_name='practica',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='practica',
            name='imagen',
        ),
    ]
